[platformio]
src_dir = .github/sketches/ci_test

[env]
framework = arduino
lib_deps = ./

[uno]
platform = atmelavr
board = uno

[esp8266]
platform = espressif8266
board = nodemcuv2

[esp32]
platform = espressif32
board = esp32dev

[env:uno_debug_on]
extends = uno
build_flags = -DDEBUG=true

[env:uno_debug_off]
extends = uno
build_flags = -DDEBUG=false

[env:esp8266_debug_on]
extends = esp8266
build_flags = -DDEBUG=true

[env:esp8266_debug_off]
extends = esp8266
build_flags = -DDEBUG=false

[env:esp32_debug_on]
extends = esp32
build_flags = -DDEBUG=true

[env:esp32_debug_off]
extends = esp32
build_flags = -DDEBUG=false
