[platformio]
src_dir = .github/sketches/ci_test

[env]
framework = arduino
lib_deps = ./

[env:uno_debug_on]
platform = atmelavr
board = uno
build_flags = -DDEBUG=1

[env:uno_debug_off]
platform = atmelavr
board = uno
build_flags = -DDEBUG=0

[env:esp8266_debug_on]
platform = espressif8266
board = nodemcuv2
build_flags = -DDEBUG=1

[env:esp8266_debug_off]
platform = espressif8266
board = nodemcuv2
build_flags = -DDEBUG=0

[env:esp32_debug_on]
platform = espressif32
board = esp32dev
build_flags = -DDEBUG=1

[env:esp32_debug_off]
platform = espressif32
board = esp32dev
build_flags = -DDEBUG=0
